apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-secret-sync.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-secret-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-secret-sync.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
