replicaCount: 1

image:
  repository: git.stropus.dev/ops/kube-secret-sync
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

configuration:
  SYNC_CONFIGS: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling: {}
nodeSelector: {}
tolerations: []
affinity: {}
