version: 29
jobs:
- name: Publish Image
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageWithKanikoStep
    name: publish docker image
    destinations: '@server_host@/@project_path@:latest'
    builtInRegistryAccessTokenSecret: ci-token
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: ops/kube-secret-sync
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
