version: 29
jobs:
- name: Publish Image
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageWithKanikoStep
    name: publish docker image
    destinations: '@server_host@/@project_path@:latest @server_host@/@project_path@:@tag@'
    builtInRegistryAccessTokenSecret: ci-token
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    branches: main
    projects: ops/kube-secret-sync
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/emmorts/kube-secret-sync
    passwordSecret: github-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
