version: 29
jobs:
- name: Publish Image
  steps:
  - !BuildImageWithKanikoStep
    name: Build and Publish
    buildContext: .
    destinations: ops/kube-secret-sync:latest
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
